apiVersion: apps/v1
kind: Deployment
metadata:
  name: sw-restapi
spec:
  selector:
    matchLabels:
      app: sw-restapi
  template:
    metadata:
      labels:
        app: sw-restapi
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '8080'
    spec:
      nodeSelector:
        pooltype: apps
        kubernetes.io/os: linux
      tolerations:
        - key: 'kubernetes.azure.com/scalesetpriority'
          operator: 'Equal'
          value: 'spot'
          effect: 'NoSchedule'
      automountServiceAccountToken: false
      containers:
        - name: sw-restapi
          image: ghcr.io/goncalvesj/sw-rest:0.0.1
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - NET_RAW
          envFrom:
            - configMapRef:
                name: sw-restapi-config
          resources:
            requests:
              memory: '64Mi'
              cpu: '1m'
              ephemeral-storage: '1M'
            limits:
              memory: '128Mi'
              cpu: '500m'
              ephemeral-storage: '1Gi'
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: sw-restapi
spec:
  selector:
    app: sw-restapi
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
