version: '3.4'

services:
  ado-agent-1:
    image: jprgacr.azurecr.io/devops/ado-agent:dev
    environment:
      - AZP_AGENT_NAME=ado-agent-1
      - AZP_TOKEN=
      - AZP_URL=
    build:
      context: .
      dockerfile: AzDevOps/Dockerfile

  ado-agent-2:
    image: jprgacr.azurecr.io/devops/ado-agent:dev
    environment:
      - AZP_AGENT_NAME=ado-agent-2
      - AZP_TOKEN=
      - AZP_URL=
    build:
      context: .
      dockerfile: AzDevOps/Dockerfile

  ado-agent-3:
    image: jprgacr.azurecr.io/devops/ado-agent:dev
    environment:
      - AZP_AGENT_NAME=ado-agent-3
      - AZP_TOKEN=
      - AZP_URL=
    build:
      context: .
      dockerfile: AzDevOps/Dockerfile
