name: DevOps Agents Infrastructure Pipeline
on:
  push:
    branches:
      - master
    paths:
      - 'Docker/**'
  pull_request:
    branches:
      - master
    paths:
      - 'Docker/**'
  workflow_dispatch:

env:
  linux-context: 'Docker'
  linux-dockerfile-location: 'ADO/Linux/Dockerfile'
  linux-image-tag: 'devops/ado-agent-linux'
  windows-context: 'ADO/Windows'
  windows-dockerfile-location: 'Dockerfile'  
  windows-image-tag: 'devops/ado-agent-windows'

permissions:
  id-token: write
  contents: read

jobs:
  build-push-ado-linux:
    name: Build and Push ADO Linux Agent to Azure Container Registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure ACR Login
        run: |
          az acr login -n ${{ secrets.AZURE_ACR_NAME }}

      - name: Build the Docker image
        run: |
          cd ${{ env.linux-context }}
          docker build -f ${{ env.linux-dockerfile-location }} \
          -t ${{ secrets.AZURE_ACR_NAME }}/${{ env.linux-image-tag }}:$GITHUB_RUN_ID \
          -t ${{ secrets.AZURE_ACR_NAME }}/${{ env.linux-image-tag }}:latest .

      - name: Push the Docker image
        if: github.ref == 'refs/heads/master'
        run: |
          docker push ${{ secrets.AZURE_ACR_NAME }}/${{ env.linux-image-tag }}:$GITHUB_RUN_ID
          docker push ${{ secrets.AZURE_ACR_NAME }}/${{ env.linux-image-tag }}:latest

  build-push-ado-windows:
    name: Build and Push ADO Windows Agent to Azure Container Registry
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure ACR Login
        run: |
          az acr login -n ${{ secrets.AZURE_ACR_NAME }}

      - name: Build the Docker image
        run: |
          cd ${{ env.windows-context }}
          docker build -f ${{ env.windows-dockerfile-location }} `
          -t ${{ secrets.AZURE_ACR_NAME }}/${{ env.windows-image-tag }}:$env:GITHUB_RUN_ID `
          -t ${{ secrets.AZURE_ACR_NAME }}/${{ env.windows-image-tag }}:latest .

      - name: Push the Docker image
        if: github.ref == 'refs/heads/master'
        run: |
          docker push ${{ secrets.AZURE_ACR_NAME }}/${{ env.windows-image-tag }}:$env:GITHUB_RUN_ID
          docker push ${{ secrets.AZURE_ACR_NAME }}/${{ env.windows-image-tag }}:latest
